# Generated by Django 5.1.7 on 2025-03-19 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[("IT", "IT"), ("HR", "HR"), ("FINANCE", "Finance")], max_length=10
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        upload_to="resumes/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "docx"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="candidates__created_d94c2e_idx"),
                    models.Index(fields=["department"], name="candidates__departm_db2efd_idx"),
                ],
            },
        ),
    ]
